# Generated by Django 4.0.3 on 2022-04-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0001_Creacion_tabla_Usuarios'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
