# Generated by Django 4.0.3 on 2022-04-06 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_Creacion_Tabla_Etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='categoria',
            field=models.CharField(choices=[('TODO', 'TO_DO'), ('IP', 'IN_PROGESS'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='TODO', max_length=45),
        ),
        migrations.AddField(
            model_name='tareas',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='created_et', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='etiquetas',
            field=models.ManyToManyField(related_name='tareas', to='gestion.etiqueta'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fechaCaducidad',
            field=models.DateTimeField(db_column='fecha_caducidad', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='importancia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='nombre',
            field=models.CharField(default='Nada', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='tareas',
            table='tareas',
        ),
    ]
