# Generated by Django 4.0.3 on 2022-04-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_tareas_categoria_tareas_createdat_tareas_etiquetas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
